/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tamagotchi;



import fonts.Fuentes;
import java.io.File;
import javax.swing.border.TitledBorder;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
    import javax.sound.sampled.*;
import javax.swing.ImageIcon;
/**
 *
 * @author marco
 */
public class Tienda extends javax.swing.JFrame {

    Fuentes tipoFuente;
    int xMouse,yMouse;
    Connection conn = null;
    private static final String DB_URL = "jdbc:sqlite:./sqlite-tools-win32-x86-3410200/sqlite-tools-win32-x86-3410200/tamagotchi.db";
    private final String chiclin="src/music/chiclin.wav";
    private final ImageIcon sold = new ImageIcon("src/img/sold.png");
    
    public Tienda() {
        initComponents();
        setVisible(true);
        tipoFuente = new Fuentes();
        jLabel1.setFont(tipoFuente.fuente(tipoFuente.ARCADE, 1, 45));
        TitledBorder titledBorder = (TitledBorder)jPanel2.getBorder();
        titledBorder.setTitleFont(tipoFuente.fuente(tipoFuente.ARCADE, 1, 25));
        TitledBorder titledBorder2 = (TitledBorder)jPanel3.getBorder();
        titledBorder2.setTitleFont(tipoFuente.fuente(tipoFuente.ARCADE, 1, 25));
        TitledBorder titledBorder3 = (TitledBorder)jPanel5.getBorder();
        titledBorder3.setTitleFont(tipoFuente.fuente(tipoFuente.ARCADE, 1, 25));
        jLabel17.setFont(tipoFuente.fuente(tipoFuente.ARCADE, 1, 18));
        jLabel18.setFont(tipoFuente.fuente(tipoFuente.ARCADE, 1, 18));
        jLabel19.setFont(tipoFuente.fuente(tipoFuente.ARCADE, 1, 18));
        jLabel20.setFont(tipoFuente.fuente(tipoFuente.ARCADE, 1, 18));
        jLabel21.setFont(tipoFuente.fuente(tipoFuente.ARCADE, 1, 18));
        jLabel22.setFont(tipoFuente.fuente(tipoFuente.ARCADE, 1, 18));
        jLabel23.setFont(tipoFuente.fuente(tipoFuente.ARCADE, 1, 18));
        jLabel24.setFont(tipoFuente.fuente(tipoFuente.ARCADE, 1, 18));
        jLabel27.setFont(tipoFuente.fuente(tipoFuente.ARCADE, 1, 18));
        jLabel30.setFont(tipoFuente.fuente(tipoFuente.ARCADE, 1, 18));
        jLabel35.setFont(tipoFuente.fuente(tipoFuente.ARCADE, 1, 18));
        jLabel36.setFont(tipoFuente.fuente(tipoFuente.ARCADE, 1, 18));
        jLabel39.setFont(tipoFuente.fuente(tipoFuente.ARCADE, 1, 18));
        jLabel42.setFont(tipoFuente.fuente(tipoFuente.ARCADE, 1, 18));
        
        
        try {
        Class.forName("org.sqlite.JDBC");
        conn = DriverManager.getConnection(DB_URL);
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        }   
        catch (SQLException ex) {
                Logger.getLogger(Tienda.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        actualizarIconos();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Tienda");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel1MouseDragged(evt);
            }
        });
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letra-x.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Comidas"));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/water.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 24, 5, 24);
        jPanel2.add(jLabel3, gridBagConstraints);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buy.png"))); // NOI18N
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 14, 0, 14);
        jPanel2.add(jLabel4, gridBagConstraints);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pancake.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 24, 5, 24);
        jPanel2.add(jLabel5, gridBagConstraints);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buy.png"))); // NOI18N
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 14, 0, 14);
        jPanel2.add(jLabel6, gridBagConstraints);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/omelette.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 24, 5, 24);
        jPanel2.add(jLabel7, gridBagConstraints);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buy.png"))); // NOI18N
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 14, 0, 14);
        jPanel2.add(jLabel8, gridBagConstraints);

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/comida.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 24, 5, 24);
        jPanel2.add(jLabel9, gridBagConstraints);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buy.png"))); // NOI18N
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 14, 0, 14);
        jPanel2.add(jLabel10, gridBagConstraints);

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/croissant.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 24, 5, 24);
        jPanel2.add(jLabel11, gridBagConstraints);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buy.png"))); // NOI18N
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 14, 0, 14);
        jPanel2.add(jLabel12, gridBagConstraints);

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eggs.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 24, 5, 24);
        jPanel2.add(jLabel13, gridBagConstraints);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buy.png"))); // NOI18N
        jLabel14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 14, 0, 14);
        jPanel2.add(jLabel14, gridBagConstraints);

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pizza.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 24, 5, 24);
        jPanel2.add(jLabel15, gridBagConstraints);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buy.png"))); // NOI18N
        jLabel16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 14, 0, 14);
        jPanel2.add(jLabel16, gridBagConstraints);

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("<html><div style='text-align: center;'>Agua<br>10$</div></html>");
        jPanel2.add(jLabel17, new java.awt.GridBagConstraints());

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("<html><div style='text-align: center;'>Pancakes<br>20$</div></html>");
        jPanel2.add(jLabel18, new java.awt.GridBagConstraints());

        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("<html><div style='text-align: center;'>Tostada<br>25$</div></html>");
        jPanel2.add(jLabel19, new java.awt.GridBagConstraints());

        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("<html><div style='text-align: center;'>Burguer<br>30$</div></html>");
        jPanel2.add(jLabel20, new java.awt.GridBagConstraints());

        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("<html><div style='text-align: center;'>Croissant<br>15$</div></html>");
        jPanel2.add(jLabel21, new java.awt.GridBagConstraints());

        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("<html><div style='text-align: center;'>Huevos<br>35$</div></html>");
        jPanel2.add(jLabel22, new java.awt.GridBagConstraints());

        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("<html><div style='text-align: center;'>Pizza<br>15$</div></html>");
        jPanel2.add(jLabel23, new java.awt.GridBagConstraints());

        jPanel3.setBackground(new java.awt.Color(204, 255, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Ropa"));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/abrigo.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.insets = new java.awt.Insets(3, 4, 3, 4);
        jPanel3.add(jLabel25, gridBagConstraints);

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buy.png"))); // NOI18N
        jLabel26.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel26MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.insets = new java.awt.Insets(3, 4, 3, 4);
        jPanel3.add(jLabel26, gridBagConstraints);

        jLabel24.setText("<html><div style='text-align: center;'>Abrigo<br>100$</div></html>");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.insets = new java.awt.Insets(3, 4, 3, 4);
        jPanel3.add(jLabel24, gridBagConstraints);

        jLabel27.setText("<html><div style='text-align: center;'>Sudadera<br>100$</div></html>");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.insets = new java.awt.Insets(3, 4, 3, 4);
        jPanel3.add(jLabel27, gridBagConstraints);

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/sudadera.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.insets = new java.awt.Insets(3, 4, 3, 4);
        jPanel3.add(jLabel28, gridBagConstraints);

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buy.png"))); // NOI18N
        jLabel29.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel29.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel29MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.insets = new java.awt.Insets(3, 4, 3, 4);
        jPanel3.add(jLabel29, gridBagConstraints);

        jLabel30.setText("<html><div style='text-align: center;'>Bañador<br>100$</div></html>");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.insets = new java.awt.Insets(3, 4, 3, 4);
        jPanel3.add(jLabel30, gridBagConstraints);

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bañador.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.insets = new java.awt.Insets(3, 4, 3, 4);
        jPanel3.add(jLabel31, gridBagConstraints);

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buy.png"))); // NOI18N
        jLabel32.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel32.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel32MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.insets = new java.awt.Insets(3, 4, 3, 4);
        jPanel3.add(jLabel32, gridBagConstraints);

        jPanel5.setBackground(new java.awt.Color(204, 255, 204));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Accesorios"));
        jPanel5.setLayout(new java.awt.GridBagLayout());

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cama.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.insets = new java.awt.Insets(3, 4, 3, 4);
        jPanel5.add(jLabel33, gridBagConstraints);

        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buy.png"))); // NOI18N
        jLabel34.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel34.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel34MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.insets = new java.awt.Insets(3, 4, 3, 4);
        jPanel5.add(jLabel34, gridBagConstraints);

        jLabel35.setText("<html><div style='text-align: center;'>Cama<br>100$</div></html>");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.insets = new java.awt.Insets(3, 4, 3, 4);
        jPanel5.add(jLabel35, gridBagConstraints);

        jLabel36.setText("<html><div style='text-align: center;'>Bolsas<br>10$</div></html>");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.insets = new java.awt.Insets(3, 4, 3, 4);
        jPanel5.add(jLabel36, gridBagConstraints);

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bolsas.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.insets = new java.awt.Insets(3, 4, 3, 4);
        jPanel5.add(jLabel37, gridBagConstraints);

        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buy.png"))); // NOI18N
        jLabel38.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel38.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel38MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.insets = new java.awt.Insets(3, 4, 3, 4);
        jPanel5.add(jLabel38, gridBagConstraints);

        jLabel39.setText("<html><div style='text-align: center;'>Jabón<br>10$</div></html>");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.insets = new java.awt.Insets(3, 4, 3, 4);
        jPanel5.add(jLabel39, gridBagConstraints);

        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/jabon.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.insets = new java.awt.Insets(3, 4, 3, 4);
        jPanel5.add(jLabel40, gridBagConstraints);

        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buy.png"))); // NOI18N
        jLabel41.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel41.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel41MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.insets = new java.awt.Insets(3, 4, 3, 4);
        jPanel5.add(jLabel41, gridBagConstraints);

        jLabel42.setText("<html><div style='text-align: center;'>Cadena<br>300$</div></html>");
        jLabel42.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.insets = new java.awt.Insets(3, 4, 3, 4);
        jPanel5.add(jLabel42, gridBagConstraints);

        jLabel44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buy.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.insets = new java.awt.Insets(3, 4, 3, 4);
        jPanel5.add(jLabel44, gridBagConstraints);

        jLabel45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cadena.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        jPanel5.add(jLabel45, gridBagConstraints);

        jLabel46.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buy.png"))); // NOI18N
        jLabel46.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel46.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel46MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        jPanel5.add(jLabel46, gridBagConstraints);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 869, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jLabel1MousePressed

    private void jLabel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_jLabel1MouseDragged

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        try {
            Statement stmt = conn.createStatement();

            ResultSet rsTamagotchi = stmt.executeQuery("SELECT dinero FROM Tamagotchi WHERE id = 1");
            if (rsTamagotchi.next()) {
                int dinero = rsTamagotchi.getInt("dinero");

                if (dinero > 10) {
                    reproducirSonido();

                    String sql = "UPDATE Tamagotchi SET dinero = dinero - 10 WHERE id = 1";
                    stmt.executeUpdate(sql);

                    sql = "UPDATE Comida SET agua = agua + 1 WHERE mascota_id = 1";
                    stmt.executeUpdate(sql);
                }
            }
            rsTamagotchi.close();
            stmt.close();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }

    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        try {
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery("SELECT dinero FROM tamagotchi WHERE id = 1");
            
            if (rs.getInt("dinero") > 20) {
                reproducirSonido();

                String sql = "UPDATE Comida SET pancakes = pancakes + 1 WHERE mascota_id = 1";
                stmt.executeUpdate(sql);

                sql = "UPDATE Tamagotchi SET dinero = dinero - 20 WHERE id = 1";
                stmt.executeUpdate(sql);

                rs.close();
                stmt.close();
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }

    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        try {
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery("SELECT dinero FROM Tamagotchi WHERE id = 1");

            if (rs.getInt("dinero") > 25) {
                reproducirSonido();

                String sql = "UPDATE Comida SET tostadas = tostadas + 1 WHERE mascota_id = 1";
                stmt.executeUpdate(sql);

                sql = "UPDATE Tamagotchi SET dinero = dinero - 25 WHERE id = 1";
                stmt.executeUpdate(sql);

                rs.close();
                stmt.close();
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }

    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        try {
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery("SELECT dinero FROM Tamagotchi WHERE id = 1");

            if (rs.getInt("dinero") > 30) {
                reproducirSonido();

                String sql = "UPDATE Comida SET burguer = burguer + 1 WHERE mascota_id = 1";
                stmt.executeUpdate(sql);

                sql = "UPDATE Tamagotchi SET dinero = dinero - 30 WHERE id = 1";
                stmt.executeUpdate(sql);

                rs.close();
                stmt.close();
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        try {
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery("SELECT dinero FROM Tamagotchi WHERE id = 1");

            if (rs.getInt("dinero") > 15) {
                reproducirSonido();

                String sql = "UPDATE Comida SET croissant = croissant + 1 WHERE mascota_id = 1";
                stmt.executeUpdate(sql);

                sql = "UPDATE Tamagotchi SET dinero = dinero - 15 WHERE id = 1";
                stmt.executeUpdate(sql);

                rs.close();
                stmt.close();
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        try {
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery("SELECT dinero FROM Tamagotchi WHERE id = 1");

            if (rs.getInt("dinero") > 35) {
                reproducirSonido();

                String sql = "UPDATE Comida SET huevos = huevos + 1 WHERE mascota_id = 1";
                stmt.executeUpdate(sql);

                sql = "UPDATE Tamagotchi SET dinero = dinero - 35 WHERE id = 1";
                stmt.executeUpdate(sql);

                rs.close();
                stmt.close();
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        try {
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery("SELECT dinero FROM Tamagotchi WHERE id = 1");

            if (rs.getInt("dinero") > 15) {
                reproducirSonido();

                String sql = "UPDATE Comida SET pizza = pizza + 1 WHERE mascota_id = 1";
                stmt.executeUpdate(sql);

                sql = "UPDATE Tamagotchi SET dinero = dinero - 15 WHERE id = 1";
                stmt.executeUpdate(sql);

                rs.close();
                stmt.close();
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }

    }//GEN-LAST:event_jLabel16MouseClicked

    private void jLabel38MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel38MouseClicked
        try {
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery("SELECT dinero FROM Tamagotchi WHERE id = 1");

            if (rs.getInt("dinero") > 10) {
                reproducirSonido();

                String sql = "UPDATE Inventario SET bolsas = bolsas + 1 WHERE mascota_id = 1";
                stmt.executeUpdate(sql);

                sql = "UPDATE Tamagotchi SET dinero = dinero - 10 WHERE id = 1";
                stmt.executeUpdate(sql);

                rs.close();
                stmt.close();
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jLabel38MouseClicked

    private void jLabel41MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel41MouseClicked
        try {
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery("SELECT dinero FROM Tamagotchi WHERE id = 1");

            if (rs.getInt("dinero") > 10) {
                reproducirSonido();

                String sql = "UPDATE Inventario SET jabon = jabon + 1 WHERE mascota_id = 1";
                stmt.executeUpdate(sql);

                sql = "UPDATE Tamagotchi SET dinero = dinero - 10 WHERE id = 1";
                stmt.executeUpdate(sql);

                rs.close();
                stmt.close();
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }

    }//GEN-LAST:event_jLabel41MouseClicked

    private void jLabel26MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel26MouseClicked
        try {
            String sqlCheckRopa = "SELECT abrigo FROM Ropa WHERE mascota_id = 1";
            String sqlCheckDinero = "SELECT dinero FROM Tamagotchi WHERE id = 1";

            PreparedStatement stmtCheckRopa = conn.prepareStatement(sqlCheckRopa);
            PreparedStatement stmtCheckDinero = conn.prepareStatement(sqlCheckDinero);

            ResultSet rsRopa = stmtCheckRopa.executeQuery();
            ResultSet rsDinero = stmtCheckDinero.executeQuery();

            boolean abrigoComprado = rsRopa.next() && rsRopa.getBoolean("abrigo");
            int dineroDisponible = rsDinero.next() ? rsDinero.getInt("dinero") : 0;

            if (!abrigoComprado && dineroDisponible >= 100) {
                String sqlUpdateRopa = "UPDATE Ropa SET abrigo = 1 WHERE mascota_id = 1";
                String sqlUpdateDinero = "UPDATE Tamagotchi SET dinero = dinero - 100 WHERE id = 1";

                PreparedStatement stmtUpdateRopa = conn.prepareStatement(sqlUpdateRopa);
                PreparedStatement stmtUpdateDinero = conn.prepareStatement(sqlUpdateDinero);

                stmtUpdateRopa.executeUpdate();
                stmtUpdateDinero.executeUpdate();

                stmtUpdateRopa.close();
                stmtUpdateDinero.close();

                reproducirSonido();
                jLabel26.setIcon(sold);
            }

            rsRopa.close();
            rsDinero.close();
            stmtCheckRopa.close();
            stmtCheckDinero.close();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }



    }//GEN-LAST:event_jLabel26MouseClicked

    private void jLabel29MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel29MouseClicked
        try {
            String sqlCheckRopa = "SELECT sudadera FROM Ropa WHERE mascota_id = 1";
            String sqlCheckDinero = "SELECT dinero FROM Tamagotchi WHERE id = 1";

            PreparedStatement stmtCheckRopa = conn.prepareStatement(sqlCheckRopa);
            PreparedStatement stmtCheckDinero = conn.prepareStatement(sqlCheckDinero);

            ResultSet rsRopa = stmtCheckRopa.executeQuery();
            ResultSet rsDinero = stmtCheckDinero.executeQuery();

            boolean sudaderaComprada = rsRopa.next() && rsRopa.getBoolean("sudadera");
            int dineroDisponible = rsDinero.next() ? rsDinero.getInt("dinero") : 0;

            if (!sudaderaComprada && dineroDisponible >= 100) {
                String sqlUpdateRopa = "UPDATE Ropa SET sudadera = 1 WHERE mascota_id = 1";
                String sqlUpdateDinero = "UPDATE Tamagotchi SET dinero = dinero - 100 WHERE id = 1";

                PreparedStatement stmtUpdateRopa = conn.prepareStatement(sqlUpdateRopa);
                PreparedStatement stmtUpdateDinero = conn.prepareStatement(sqlUpdateDinero);

                stmtUpdateRopa.executeUpdate();
                stmtUpdateDinero.executeUpdate();

                stmtUpdateRopa.close();
                stmtUpdateDinero.close();

                reproducirSonido();
                jLabel29.setIcon(sold);
            }

            rsRopa.close();
            rsDinero.close();
            stmtCheckRopa.close();
            stmtCheckDinero.close();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }


    }//GEN-LAST:event_jLabel29MouseClicked

    private void jLabel32MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel32MouseClicked
        try {
            String sqlCheckRopa = "SELECT banador FROM Ropa WHERE mascota_id = 1";
            String sqlCheckDinero = "SELECT dinero FROM Tamagotchi WHERE id = 1";

            PreparedStatement stmtCheckRopa = conn.prepareStatement(sqlCheckRopa);
            PreparedStatement stmtCheckDinero = conn.prepareStatement(sqlCheckDinero);

            ResultSet rsRopa = stmtCheckRopa.executeQuery();
            ResultSet rsDinero = stmtCheckDinero.executeQuery();

            boolean sudaderaComprada = rsRopa.next() && rsRopa.getBoolean("banador");
            int dineroDisponible = rsDinero.next() ? rsDinero.getInt("dinero") : 0;

            if (!sudaderaComprada && dineroDisponible >= 100) {
                String sqlUpdateRopa = "UPDATE Ropa SET banador = 1 WHERE mascota_id = 1";
                String sqlUpdateDinero = "UPDATE Tamagotchi SET dinero = dinero - 100 WHERE id = 1";

                PreparedStatement stmtUpdateRopa = conn.prepareStatement(sqlUpdateRopa);
                PreparedStatement stmtUpdateDinero = conn.prepareStatement(sqlUpdateDinero);

                stmtUpdateRopa.executeUpdate();
                stmtUpdateDinero.executeUpdate();

                stmtUpdateRopa.close();
                stmtUpdateDinero.close();

                reproducirSonido();
                jLabel32.setIcon(sold);
            }

            rsRopa.close();
            rsDinero.close();
            stmtCheckRopa.close();
            stmtCheckDinero.close();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }

    }//GEN-LAST:event_jLabel32MouseClicked

    private void jLabel34MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel34MouseClicked
        try {
            String sqlCheckCama = "SELECT cama FROM Inventario WHERE mascota_id = 1";
            String sqlCheckDinero = "SELECT dinero FROM Tamagotchi WHERE id = 1";

            PreparedStatement stmtCheckCama = conn.prepareStatement(sqlCheckCama);
            PreparedStatement stmtCheckDinero = conn.prepareStatement(sqlCheckDinero);

            ResultSet rsCama = stmtCheckCama.executeQuery();
            ResultSet rsDinero = stmtCheckDinero.executeQuery();

            boolean camaComprada = rsCama.next() && rsCama.getBoolean("cama");
            int dineroDisponible = rsDinero.next() ? rsDinero.getInt("dinero") : 0;

            if (!camaComprada && dineroDisponible >= 100) {
                String sqlUpdateCama = "UPDATE Inventario SET cama = 1 WHERE mascota_id = 1";
                String sqlUpdateDinero = "UPDATE Tamagotchi SET dinero = dinero - 100 WHERE id = 1";

                PreparedStatement stmtUpdateCama = conn.prepareStatement(sqlUpdateCama);
                PreparedStatement stmtUpdateDinero = conn.prepareStatement(sqlUpdateDinero);

                stmtUpdateCama.executeUpdate();
                stmtUpdateDinero.executeUpdate();

                stmtUpdateCama.close();
                stmtUpdateDinero.close();

                reproducirSonido();
                jLabel34.setIcon(sold);
            }

            rsCama.close();
            rsDinero.close();
            stmtCheckCama.close();
            stmtCheckDinero.close();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }


    }//GEN-LAST:event_jLabel34MouseClicked

    private void jLabel46MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel46MouseClicked
        try {
            String sqlCheckCadena = "SELECT cadena FROM Inventario WHERE mascota_id = 1";
            String sqlCheckDinero = "SELECT dinero FROM Tamagotchi WHERE id = 1";

            PreparedStatement stmtCheckCadena = conn.prepareStatement(sqlCheckCadena);
            PreparedStatement stmtCheckDinero = conn.prepareStatement(sqlCheckDinero);

            ResultSet rsCadena = stmtCheckCadena.executeQuery();
            ResultSet rsDinero = stmtCheckDinero.executeQuery();

            boolean cadenaComprada = rsCadena.next() && rsCadena.getBoolean("cadena");
            int dineroDisponible = rsDinero.next() ? rsDinero.getInt("dinero") : 0;

            if (!cadenaComprada && dineroDisponible >= 300) {
                String sqlUpdateCadena = "UPDATE Inventario SET cadena = 1 WHERE mascota_id = 1";
                String sqlUpdateDinero = "UPDATE Tamagotchi SET dinero = dinero - 300 WHERE id = 1";

                PreparedStatement stmtUpdateCadena = conn.prepareStatement(sqlUpdateCadena);
                PreparedStatement stmtUpdateDinero = conn.prepareStatement(sqlUpdateDinero);

                stmtUpdateCadena.executeUpdate();
                stmtUpdateDinero.executeUpdate();

                stmtUpdateCadena.close();
                stmtUpdateDinero.close();

                reproducirSonido();
                jLabel46.setIcon(sold);
            }

            rsCadena.close();
            rsDinero.close();
            stmtCheckCadena.close();
            stmtCheckDinero.close();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }


    }//GEN-LAST:event_jLabel46MouseClicked

    public void actualizarIconos()
            {try {
            String sqlRopa = "SELECT abrigo, banador, sudadera FROM Ropa WHERE mascota_id = 1";
            String sqlInventario = "SELECT cadena, cama FROM Inventario WHERE mascota_id = 1";

            PreparedStatement stmtRopa = conn.prepareStatement(sqlRopa);
            PreparedStatement stmtInventario = conn.prepareStatement(sqlInventario);

            ResultSet rsRopa = stmtRopa.executeQuery();
            ResultSet rsInventario = stmtInventario.executeQuery();

            boolean abrigo = false;
            boolean banador = false;
            boolean sudadera = false;
            boolean cadena = false;
            boolean cama= false;

            if (rsRopa.next()) {
                abrigo = rsRopa.getBoolean("abrigo");
                if(abrigo){jLabel26.setIcon(sold);}
                banador = rsRopa.getBoolean("banador");
                if(banador){jLabel32.setIcon(sold);}
                sudadera = rsRopa.getBoolean("sudadera");
                if(sudadera){jLabel29.setIcon(sold);}

            }

            if (rsInventario.next()) {
                cadena = rsInventario.getBoolean("cadena");
                if(cadena){jLabel46.setIcon(sold);}
                cama = rsInventario.getBoolean("cama");
                if(cama){jLabel34.setIcon(sold);}


            }

            rsRopa.close();
            rsInventario.close();
            stmtRopa.close();
            stmtInventario.close();

        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        }
    
    
    public void reproducirSonido() {
    try {
        File archivo = new File(chiclin);
        AudioInputStream audioInputStream = AudioSystem.getAudioInputStream(archivo);
        Clip clip = AudioSystem.getClip();
        clip.open(audioInputStream);
        clip.start();
    } catch(Exception ex) {
        ex.printStackTrace();
    }
}


    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tienda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
